<?php

/*
	Do not edit this file manually. This copy of global file is overwritten
	by extensions editor.
*/

$installed_extensions = array (
  1 => 
  array (
    'package' => 'dimension',
    'name' => 'dimension',
    'version' => '-',
    'available' => '',
    'type' => 'extension',
    'path' => 'modules/dimension',
    'active' => 1,
  ),
);
?>